// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function MainPage(Props) {
  return React.createElement("div", undefined, "Hello world");
}

var make = MainPage;

exports.make = make;
/* react Not a pure module */
