// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Apollo = require("./graphql/Apollo.bs.js");
var UserList = require("./users/UserList.bs.js");
var Client = require("@apollo/client");

function MainPage(Props) {
  return React.createElement(Client.ApolloProvider, {
              client: Apollo.client,
              children: React.createElement("div", undefined, React.createElement("div", undefined, "Hello world"), React.createElement(UserList.make, {}))
            });
}

var make = MainPage;

exports.make = make;
/* react Not a pure module */
