// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MainPage = require("./app/MainPage.bs.js");
var ReactDom = require("react-dom");
var Caml_option = require("rescript/lib/js/caml_option.js");

var optRoot = document.getElementById("root");

if (!(optRoot == null)) {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(MainPage.make, {})
          }), optRoot);
}

var optRoot$1 = (optRoot == null) ? undefined : Caml_option.some(optRoot);

exports.optRoot = optRoot$1;
/* optRoot Not a pure module */
