// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UserList from "./components/UserList.mjs";

function $$default(param) {
  return React.createElement("div", undefined, React.createElement(UserList.make, {}));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
